### ISSUE TITLE
Issue with weird tables

### ISSUE THREAD

**Issue by Evpok** [portstrom/parse_wiki_text#9]
The following wikicode is legal, though weird

```wikicode
{|
|}
;
{|
*
|}
```

But parsing it (any config) panics with the following backtrace

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.3/src/list.rs:97:18
stack backtrace:
[snip]
   6: parse_wiki_text::list::parse_list_end_of_line
             at /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.3/src/list.rs:97
   7: parse_wiki_text::line::parse_end_of_line
             at /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.3/src/line.rs:156
   8: parse_wiki_text::parse::parse
             at /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.3/src/parse.rs:74
   9: parse_wiki_text::configuration::<impl parse_wiki_text::Configuration>::parse
             at /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.3/src/configuration.rs:155
[snip]
```
The `;` and the `*` seem instrumental in this failure (after removing one of them, parsing works), strange as it may seem.

An example of an actual page that triggers the issue is https://fr.wikipedia.org/wiki/Francesco_Yates.

**Comment by portstrom** [comment]
Fixed. Thanks for reporting. There was a bug causing anything that comes after a horizontal divider or a table to be incorrectly parsed. This leads to empty list items not being terminated at the end of the line, causing anything that comes after the list item to be placed inside it. Since tables are not supposed to  be possible to place inside list items, the panic is caused.
